Enforce tsdocs for exported functions
Brainicism/KMQ_Discord pull request #1128
Opened 2021-11-25 11:01 UTC by Brainicism

2021-11-25 11:23 UTC, taahamahdi requested changes

2021-11-25 11:23 UTC, taahamahdi commented on src/commands/game_commands/exp.ts
> + * @returns an array describing the EXP modifiers activated and their numierical value
numerical

2021-11-25 11:23 UTC, taahamahdi commented on src/commands/game_commands/exp.ts
> + * @param voteBonusExp - Whetther bonus EXP should be applied to the modifier
Whether

2021-11-25 11:23 UTC, taahamahdi commented on src/commands/game_commands/exp.ts
> + * @returns the EXP modifiered based onthe number of participants
Modifier

On the

2021-11-25 11:23 UTC, taahamahdi commented on src/commands/game_commands/exp.ts
> + * @param voteBonusExp - Whetther bonus EXP should be applied to the modifier
Whether

2021-11-25 11:23 UTC, taahamahdi commented on src/commands/game_commands/hint.ts
> + * @param message - The originiating messages
Originating message

2021-11-25 11:23 UTC, taahamahdi commented on src/events/client/shardDisconnect.ts
> + * Handles the 'shardDisconnect' event.
Other comments don't end with periods

2021-11-25 11:23 UTC, taahamahdi commented on src/events/client/voiceChannelSwitch.ts
> + * Handles teh 'voiceChannelSwitch' event
The

2021-11-25 11:23 UTC, taahamahdi commented on src/helpers/discord_utils.ts
> + * @param timeRemaining - The time remaining for the timer option
For the duration option

2021-11-25 11:23 UTC, taahamahdi commented on src/scripts/backup-kmq-database.ts
> + *
Missing

2021-11-25 11:23 UTC, taahamahdi commented on src/scripts/download-new-songs.ts
> +async function clearPartiallyCachedSongs(): Promise<void> {
Missing doc

2021-11-25 11:23 UTC, taahamahdi commented on src/structures/guild_preference.ts
> + * @param spaceDelimiter - Wheter to space delimit the final result
Whether

2021-11-25 11:23 UTC, taahamahdi commented on src/structures/team_scoreboard.ts
> +     * @param userID - The unique identifier of the player whose score is being incremented
The player's score is not being incremented

2021-11-25 17:35 UTC, Brainicism commented on src/scripts/download-new-songs.ts
> +async function clearPartiallyCachedSongs(): Promise<void> {
Function isn't exported

2021-11-26 03:34 UTC, taahamahdi approved these changes

2021-11-26 04:06 UTC, merged