Framework for localization
Brainicism/KMQ_Discord pull request #1162
Opened 2022-01-02 16:02 UTC by taahamahdi

2022-01-02 16:03 UTC, kambojk commented on package.json
> +    "mustache": "^4.2.0",
bruhhhhhhhhhh 420 lmao

2022-01-02 16:07 UTC, kambojk commented on i18n/en.json
> +	"misc.preCheck.debugServer": "You can't do that in this server.",
literally 1984

2022-01-02 16:08 UTC, kambojk commented on i18n/ko.json
> +	"misc.gameMessages.kmqServer.title.likeKmq": "Like KMQ?",
Ye

2022-01-02 16:26 UTC, kambojk reviewed
LGTM

2022-01-03 01:18 UTC, Brainicism commented on i18n/en.json
> +	"misc.preCheck.debugServer": "You can't do that in this server.",
shid

2022-01-03 01:18 UTC, Brainicism commented on i18n/ko.json
> +	"misc.gameMessages.kmqServer.title.likeKmq": "Like KMQ?",
thx

2022-01-03 21:48 UTC, Brainicism requested changes

2022-01-03 21:48 UTC, Brainicism commented on i18n/en.json
> +  "add.failure.unrecognizedGroups.added": "added",
Namespace all command translations with `command` or something similar

2022-01-03 21:48 UTC, Brainicism commented on i18n/en.json
> +  "add.failure.unrecognizedGroups.added": "added",
General note: can't you namespace these by doing something like:
command: {
    help: {
        example: {
            exclude: "...",
            include: "..."
        }
    }
}

2022-01-03 21:48 UTC, Brainicism commented on i18n/en.json
> +  "exp.explanation.rareGuess.upTo": "up to",
Translations should be full strings, not partial strings. The grammar for these might be structured differently in different languages

2022-01-03 21:56 UTC, Brainicism commented on src/helpers/discord_utils.ts
> +            title: "misc.failure.missingPermissions.title",
Title isn't translated?

2022-01-03 22:16 UTC, Brainicism commented on src/test/ci/begin.test.ts
> +state.localizer = new LocalizationManager();
Can just do this once in test_setup instead of in individual tests

2022-01-05 02:10 UTC, Brainicism requested changes

2022-01-05 05:22 UTC, taahamahdi commented on i18n/en.json
> +            "secondTourneyAllParticipant": "🎖️ Second Tourney (All Groups) Participant",
Since they're pulled directly from the badges table, there's nowhere to abstract multiple badges into one

2022-01-05 05:22 UTC, taahamahdi commented on i18n/en.json
> +    "10th": "10th",
I left these because they were generated dynamically. If we append misc to every call of getOrdinalNum, I should be able to do this

2022-01-05 06:27 UTC, Brainicism commented on i18n/en.json
> +            "secondTourneyAllParticipant": "🎖️ Second Tourney (All Groups) Participant",
So is there a point in having this subset of badges here? We can probably just keep them as english

2022-01-05 06:32 UTC, taahamahdi commented on i18n/en.json
> +            "secondTourneyAllParticipant": "🎖️ Second Tourney (All Groups) Participant",
Yeah let's keep them as English. I'll pull them out

2022-01-06 01:11 UTC, taahamahdi commented on i18n/en.json
> +    "10th": "10th",
These entries were created by `fact_generator`. For any other use of `getOrdinalNum`, how will we translate an arbitrary ordinal number? One example is in `discord_utils` when an upper and lower limit are set (`,limit: 200th to 500th (300 songs) / 8,306`)

2022-01-10 23:03 UTC, hoehoetvhss reviewed
47 Line: 'EXP' --> '경험치'

2022-01-10 23:42 UTC, hoehoetvhss commented
[ko.zip](https://github.com/Brainicism/KMQ_Discord/files/7842573/ko.zip)

We corrected the strange translations and untranslated parts we found so far.

2022-01-14 04:34 UTC, Brainicism approved these changes

2022-01-14 04:35 UTC, merged