Premium music session
Brainicism/KMQ_Discord pull request #1241
Opened 2022-03-13 09:00 UTC by taahamahdi

2022-03-13 21:32 UTC, Brainicism requested changes

2022-03-13 21:32 UTC, Brainicism commented on src/commands/admin/stats.ts
> +        const totalRounds =
This should only count game rounds

2022-03-13 21:35 UTC, taahamahdi commented on src/events/client/messageCreate.ts
> +                if (process.env.NODE_ENV === EnvType.DEV) {
If some exception is thrown in a command, it's helpful to see what line caused it. I can take it out if you want

2022-03-13 21:37 UTC, Brainicism commented on src/events/client/messageCreate.ts
> +                if (process.env.NODE_ENV === EnvType.DEV) {
You can just print the stack trace

2022-04-03 18:55 UTC, Brainicism approved these changes

2022-04-03 19:35 UTC, merged