Slash command for ,profile
Brainicism/KMQ_Discord pull request #1407
Opened 2022-07-11 23:38 UTC by taahamahdi

2022-07-11 23:39 UTC, taahamahdi commented on src/commands/game_commands/profile.ts
> +                    channel_types: undefined as never,
I can't get the compiler to stop complaining without this line

2022-07-12 02:15 UTC, Brainicism requested changes

2022-07-12 02:15 UTC, Brainicism commented on src/commands/game_commands/profile.ts
> +                    description: "Mention the user whose profile to view",
Translations missing

2022-07-12 02:15 UTC, Brainicism commented on src/commands/game_commands/profile.ts
> +                        "The user ID of the player whose profile to view",
Same here

2022-07-12 02:15 UTC, Brainicism commented on src/commands/game_commands/profile.ts
> +        if (
No need for this check

2022-07-12 02:15 UTC, Brainicism commented on src/commands/game_options/groups.ts
> +        if (
No need for this check

2022-07-13 22:51 UTC, hoehoetvhss approved these changes

2022-07-14 02:36 UTC, Brainicism submitted a review, later dismissed

2022-07-15 01:18 UTC, hoehoetvhss approved these changes

2022-07-15 01:22 UTC, merged