Slash command for ,multiguess
Brainicism/KMQ_Discord pull request #1417
Opened 2022-07-13 03:22 UTC by Brainicism

2022-07-13 03:25 UTC, taahamahdi requested changes

2022-07-13 03:25 UTC, taahamahdi commented on src/commands/admin/appcommands.ts
> +                            if (cmd.name !== "multiguess") continue;
```suggestion
```

2022-07-13 03:31 UTC, taahamahdi submitted a review, later dismissed

2022-07-13 22:57 UTC, hoehoetvhss submitted a review, later dismissed

2022-07-14 02:35 UTC, taahamahdi approved these changes

2022-07-14 02:35 UTC, merged