Slash command for ,special
Brainicism/KMQ_Discord pull request #1424
Opened 2022-07-13 04:54 UTC by Brainicism

2022-07-13 05:05 UTC, taahamahdi requested changes

2022-07-13 05:05 UTC, taahamahdi commented on src/commands/game_options/special.ts
> +                    required: true,
```suggestion
                    required: false,
```
To disable special

2022-07-13 05:06 UTC, taahamahdi approved these changes

2022-07-13 05:09 UTC, merged

2026-07-10 19:46 UTC, xtwitter112233-maker reviewed
G