Slash command for ,play
Brainicism/KMQ_Discord pull request #1428
Opened 2022-07-13 08:52 UTC by taahamahdi

2022-07-17 06:55 UTC, Brainicism commented on src/commands/game_commands/play.ts
> +                {
Both of these embed payloads are the same?

2022-07-17 07:10 UTC, Brainicism requested changes

2022-07-17 07:10 UTC, Brainicism commented on src/commands/game_commands/play.ts
> +        if (gameType === GameType.ELIMINATION) {
Can we re-use this `lives` logic for both slash command and text input cases into `PlayCommand.startGame`?

2022-07-17 07:10 UTC, Brainicism commented on src/helpers/discord_utils.ts
> +        embeds.push(generateEmbed(messageContext, payload));
Can use a map here

2022-07-17 22:15 UTC, hoehoetvhss submitted a review, later dismissed

2022-07-24 21:29 UTC, Brainicism approved these changes

2022-07-24 21:40 UTC, merged