Add tryCreateInteractionCustomPayloadAcknowledgement function
Brainicism/KMQ_Discord pull request #1429
Opened 2022-07-14 06:31 UTC by Brainicism

Use `tryCreateInteractionCustomPayloadAcknowledgement()` instead of retrofitted success/error ack functions. Bold embed titles by default
Closes #1426

2022-07-14 11:23 UTC, hoehoetvhss submitted a review, later dismissed

2022-07-15 00:30 UTC, taahamahdi requested changes

2022-07-15 00:30 UTC, taahamahdi commented on src/commands/game_commands/skip.ts
> +                    LocalizationManager.localizer.translate(
```suggestion
                    LocalizationManager.localizer.translateByLocale(
```

2022-07-15 00:30 UTC, taahamahdi commented on src/commands/game_commands/skip.ts
> +                    LocalizationManager.localizer.translate(
```suggestion
                    LocalizationManager.localizer.translateByLocale(
```

2022-07-15 00:32 UTC, taahamahdi approved these changes

2022-07-15 00:57 UTC, merged