Add slash command for ,goal
Brainicism/KMQ_Discord pull request #1441
Opened 2022-07-25 02:57 UTC by Brainicism

2022-07-25 23:54 UTC, hoehoetvhss submitted a review, later dismissed

2022-07-26 00:25 UTC, taahamahdi requested changes

2022-07-26 00:25 UTC, taahamahdi commented on src/commands/game_options/goal.ts
> +                    required: true,
Should we make it disable the goal if no args are passed? Which would mean `required: false`

2022-07-26 00:28 UTC, taahamahdi requested changes

2022-07-26 00:28 UTC, taahamahdi commented on src/commands/game_options/goal.ts
> +            await sendOptionsMessage(
I think this can be removed, otherwise it will send the options message twice on reset

2022-07-26 02:13 UTC, taahamahdi approved these changes

2022-07-26 02:14 UTC, merged