Slash command for ,listen
Brainicism/KMQ_Discord pull request #1445
Opened 2022-07-25 04:33 UTC by Brainicism

2022-07-26 00:44 UTC, taahamahdi requested changes

2022-07-26 00:44 UTC, taahamahdi commented on src/commands/game_commands/listen.ts
> +            await tryCreateInteractionSuccessAcknowledgement(
We should pass the interaction as a new argument to `sendBeginListeningSessionMessage` and use that as the interaction acknowledgement

2022-07-26 02:12 UTC, taahamahdi approved these changes

2022-07-27 11:44 UTC, hoehoetvhss approved these changes

2022-07-27 14:03 UTC, merged