Slash command for ,forceskip
Brainicism/KMQ_Discord pull request #1447
Opened 2022-07-26 01:56 UTC by Brainicism

2022-07-26 02:22 UTC, taahamahdi requested changes

2022-07-26 02:22 UTC, taahamahdi commented on src/commands/game_commands/forceskip.ts
> +                        "command.forceskip.failure.notOwner.title"
Nit: May want to rename this key to something more generic

2022-07-26 02:22 UTC, taahamahdi commented on src/commands/game_commands/skip.ts
> +                        "misc.failure.game.noneInProgress.title"
This may confuse users if `session.round.skipAchieved || session.round.finished`

2022-07-26 02:57 UTC, taahamahdi submitted a review, later dismissed

2022-07-27 11:45 UTC, hoehoetvhss approved these changes

2022-07-27 14:04 UTC, merged