Slash command for ,preset
Brainicism/KMQ_Discord pull request #1455
Opened 2022-08-07 03:19 UTC by Brainicism

2022-08-07 03:34 UTC, hoehoetvhss approved these changes

2022-08-08 03:10 UTC, taahamahdi requested changes

2022-08-08 03:10 UTC, taahamahdi commented on src/commands/game_commands/preset.ts
> +                                    "command.preset.help.example.save"
May need a new translation string for the slash command options based on the context
save : the name to save the preset as
load/delete: the name of the preset to load/delete
replace: the preset to replace
import: the unique identifier associated with the preset

2022-08-10 15:33 UTC, hoehoetvhss approved these changes

2022-08-10 15:43 UTC, merged