Support slash command localization
Brainicism/KMQ_Discord pull request #1518
Opened 2022-12-06 04:34 UTC by taahamahdi

2022-12-06 04:35 UTC, taahamahdi commented
@hoehoetvhss When you get a chance, can you take out the relevant `separated by commas` for the changes in this commit: https://github.com/Brainicism/KMQ_Discord/pull/1518/commits/a146520a62ba3f7c01b7f904e3bd9caefd04e1ce

2022-12-10 17:05 UTC, taahamahdi commented
Looks good, thanks! I've removed the whitespaces from the `name` fields because Discord expects these to be single words. Can you verify the command names still make sense in this commit? https://github.com/Brainicism/KMQ_Discord/pull/1518/commits/48fcec3c68ae577713de3b13b06462751de59e3b

2022-12-13 06:41 UTC, hoehoetvhss commented
The current translation is very different from the past. That's why everyone is making corrections, but it takes time.

2022-12-13 06:41 UTC, hoehoetvhss commented
> The current translation is very different from the past. That's why everyone is making corrections, but it takes time.

But it doesn't interfere with the use.

2022-12-15 05:34 UTC, Brainicism requested changes

2022-12-15 05:34 UTC, Brainicism commented on src/commands/admin/appcommands.ts
> +                                `command.${commandName}.help.name`
Can we throw an exception if the 'name' translation key is missing, but we're expecting it to exist? Or a test

2022-12-15 07:08 UTC, hoehoetvhss commented
Any parts that I do not understand or are difficult to translate will be left in English for later translation.

2022-12-23 19:21 UTC, Brainicism approved these changes

2022-12-23 23:47 UTC, merged