Bold names of players that got a point in scoreboard
Brainicism/KMQ_Discord pull request #823
Opened 2021-06-21 22:44 UTC by taahamahdi

2021-06-22 00:08 UTC, taahamahdi commented
![Screenshot from 2021-06-21 20-07-28](https://user-images.githubusercontent.com/14286913/122842984-67b4de00-d2cc-11eb-8349-fd41e8c6aaec.png)

2021-06-22 00:08 UTC, taahamahdi commented
![Screenshot from 2021-06-21 20-07-56](https://user-images.githubusercontent.com/14286913/122843001-713e4600-d2cc-11eb-8af2-43ea6d6b35a8.png)
Not as obvious with the smaller scoreboard

2021-07-09 23:01 UTC, Brainicism requested changes

2021-07-09 23:01 UTC, Brainicism commented on src/structures/scoreboard.ts
> +    getScoreboardEmbedFields(roundResultIDs?: Set<string>): Array<{ name: string, value: string, inline: boolean }> {
Should `roundResultIDs` be `roundWinnerIDs`?

2021-07-10 00:17 UTC, taahamahdi commented on src/structures/scoreboard.ts
> +    getScoreboardEmbedFields(roundResultIDs?: Set<string>): Array<{ name: string, value: string, inline: boolean }> {
Yeah that sounds much better, thanks

2021-07-10 02:04 UTC, Brainicism commented
Can we get an updated picture of what the scoreboard looks like

2021-07-10 02:52 UTC, taahamahdi commented
![Screenshot from 2021-07-09 22-51-21](https://user-images.githubusercontent.com/14286913/125149667-519a8080-e108-11eb-9053-8ec2d7852229.png)
![Screenshot from 2021-07-09 22-51-38](https://user-images.githubusercontent.com/14286913/125149676-57906180-e108-11eb-8c8e-1b39ee470ecf.png)
![Screenshot from 2021-07-09 22-51-53](https://user-images.githubusercontent.com/14286913/125149679-595a2500-e108-11eb-99d0-0ba698b5d46f.png)

2021-07-10 02:55 UTC, Brainicism approved these changes

2021-07-10 02:56 UTC, merged